"use client";

import { sileo } from "sileo";

import { Button } from "@/components/ui/button";
import type { EstimationInput, EstimationResult } from "@/lib/schema/estimation";
import type { ClientSummary } from "@/lib/summary";

type ProjectBriefExportProps = {
  estimationInput: EstimationInput;
  estimationResult: EstimationResult;
  clientSummary: ClientSummary;
  createdAt: string;
};

const formatNum = (v: number, decimals = 1) =>
  new Intl.NumberFormat("en-US", { maximumFractionDigits: decimals }).format(v);

function buildBriefMarkdown({
  estimationInput,
  estimationResult,
  clientSummary,
  createdAt,
}: ProjectBriefExportProps): string {
  const { hoursRange, pricingRange, baseScopePoints, riskMultiplier, urgencyMultiplier } =
    estimationResult;
  const { modules, riskLevel, urgencyLevel, hourlyRate } = estimationInput;

  const date = new Date(createdAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const lines: string[] = [];

  // Header
  lines.push(`# Project Brief`);
  lines.push(`> Generated by Jitwise · ${date}`);
  lines.push("");

  // Summary stats
  lines.push(`## Estimate at a Glance`);
  lines.push("");
  lines.push(
    `| | Min | Probable | Max |`,
    `|---|---|---|---|`,
    `| **Hours** | ${formatNum(hoursRange.min)} hrs | **${formatNum(hoursRange.probable)} hrs** | ${formatNum(hoursRange.max)} hrs |`,
    `| **Cost** | $${formatNum(pricingRange.min, 0)} | **$${formatNum(pricingRange.probable, 0)}** | $${formatNum(pricingRange.max, 0)} |`,
  );
  lines.push("");
  lines.push(
    `- Risk: **${riskLevel}** (${formatNum(riskMultiplier, 2)}x) · Urgency: **${urgencyLevel}** (${formatNum(urgencyMultiplier, 2)}x)`,
    `- Hourly rate: **$${hourlyRate}/hr** · Base scope points: **${baseScopePoints} pts**`,
  );
  lines.push("");

  // Per-module effort breakdown
  lines.push(`## Effort by Module`);
  lines.push("");
  lines.push(`| Module | Complexity | Pts | % | Probable hrs | Range | Probable cost |`);
  lines.push(`|---|---|---|---|---|---|---|`);

  const sortedModules = [...clientSummary.scope].sort((a, b) => b.points - a.points);
  for (const item of sortedModules) {
    const ratio = baseScopePoints > 0 ? item.points / baseScopePoints : 0;
    const hrs = Math.round(ratio * hoursRange.probable * 10) / 10;
    const hrsMin = Math.round(ratio * hoursRange.min * 10) / 10;
    const hrsMax = Math.round(ratio * hoursRange.max * 10) / 10;
    const cost = Math.round(ratio * pricingRange.probable);
    const mod = modules.find((m) => m.moduleId === item.moduleId);
    const provider = mod?.provider ? ` (${mod.provider})` : "";
    lines.push(
      `| ${item.name}${provider} | ${item.complexity} | ${item.points} | ${Math.round(ratio * 100)}% | ${hrs} hrs | ${hrsMin}–${hrsMax} | $${cost.toLocaleString()} |`,
    );
  }
  lines.push("");

  // Client summary
  lines.push(`## Client Summary`);
  lines.push("");
  lines.push(clientSummary.summaryText);
  lines.push("");

  // Advisor content
  if (clientSummary.advisorContent) {
    lines.push(`## Scope Advisor Findings`);
    lines.push("");
    lines.push(clientSummary.advisorContent);
    lines.push("");
  }

  // Advisor insights (structured)
  if (clientSummary.advisorInsights) {
    const { risks, questions } = clientSummary.advisorInsights;
    if (risks.length > 0) {
      lines.push(`## Risk Register`);
      lines.push("");
      for (const risk of risks) lines.push(`- ${risk}`);
      lines.push("");
    }
    if (questions.length > 0) {
      lines.push(`## Open Questions`);
      lines.push("");
      for (const q of questions) lines.push(`- ${q}`);
      lines.push("");
    }
  }

  // Scope template
  if (clientSummary.templateContent) {
    lines.push(`## Scope Template`);
    lines.push("");
    lines.push(clientSummary.templateContent);
    lines.push("");
  }

  // Estimation assumptions
  lines.push(`## Estimation Assumptions`);
  lines.push("");
  lines.push(`- Scope complexity is based on the selected modules and their complexity levels.`);
  lines.push(`- Risk multiplier (${formatNum(riskMultiplier, 2)}x) reflects uncertainty in requirements or delivery.`);
  lines.push(`- Urgency multiplier (${formatNum(urgencyMultiplier, 2)}x) reflects timeline pressure.`);
  lines.push(`- Hours are calculated as: scope points × hours-per-point × risk × urgency.`);
  lines.push(`- Cost is calculated as: hours × $${hourlyRate}/hr.`);
  lines.push(`- All ranges represent min / probable / max scenarios.`);
  lines.push("");
  lines.push(`---`);
  lines.push(`*Generated by Jitwise. This estimate reflects the scope and assumptions listed above.*`);

  return lines.join("\n");
}

export function ProjectBriefExport(props: ProjectBriefExportProps) {
  const handleExport = () => {
    const markdown = buildBriefMarkdown(props);
    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = "jitwise-project-brief.md";
    anchor.click();
    URL.revokeObjectURL(url);
    sileo.success({ title: "Project brief exported." });
  };

  return (
    <Button variant="outline" onClick={handleExport}>
      Export brief
    </Button>
  );
}
